package com.example.backend.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;

import org.hibernate.annotations.NaturalId;

import java.math.BigDecimal;
/**
 * Represents a bank account within the banking system.
 *
 * <p>Each bank account belongs to a single account holder and
 * maintains the current account balance. The account number is
 * automatically generated by the database and uniquely identifies
 * the account.
 *
 * <p>Bank accounts participate in debit, credit, and transfer
 * operations throughout the application.
 */
@Entity
@Table(name = "bank_account")
public class BankAccount {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long accountNumber;

    @Column(name = "balance", nullable = false)
    @PositiveOrZero(message = "Balance cannot be negative")
    private BigDecimal balance;

    @Column(name = "holder_name", nullable = false, length = 100, unique = true)
    @NotBlank(message = "Holder name cannot be blank")
    @Size(
            min = 2,
            max = 100,
            message = "Holder name must contain between"
                    + "{min} and {max} characters"
    )
    @NaturalId
    private String holderName;

    /**
     * Default constructor required by JPA.
     */
    public BankAccount() {
    }

    /**
     * Creates a new bank account.
     *
     * @param bal initial account balance
     * @param name name of the account holder
     */
    public BankAccount(
            final String name,
            final BigDecimal bal) {

        this.balance = bal;
        this.holderName = name;
    }

    /**
     * Returns the unique account number.
     *
     * @return account number
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Returns the current account balance.
     *
     * @return current balance
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * Returns the name of the account holder.
     *
     * @return account holder name
     */
    public String getHolderName() {
        return holderName;
    }

    /**
     * Updates the account balance.
     *
     * @param bal new account balance
     */
    public void setBalance(final BigDecimal bal) {
        this.balance = bal;
    }
}
